### ISSUE TITLE
Can not find the gif file in giphy site.

### ISSUE THREAD

**Issue by wongyouth** [wulkano/kap-giphy#2]
After I successfully upload GIF file to giphy site. I got a URL https://giphy.com/gifs/hvLvIvmLD8ItBRuZX8. But it's not accessible.

**Comment by wongyouth** [comment]
Version:
  - Kap: 2.2.0
  - kap-giphy: 0.1.0

**Comment by jordanjustice** [comment]
@wongyouth I'm guessing the default API key is no longer valid. After I signed up for my own key on [giphy](https://developers.giphy.com/), and entered it in the plugin preferences, it worked as expected.
